# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1439df804877f10117dbe34338d15eb69af873372109d59503dcc0fe7f0691175c5d1bc90f33947ff440680ee5346bc4e477db38b1cb45c821a8ebe2963f0b31

test:
  secret_key_base: d465eeb7c1a1f9bc536f9311780575b97ce84274739fe77603d36001fc096c49fc79adfe86a90d01ad6935b9ab7fd05a6e999b4e7b41a8d70847a2ce1c2993ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
